<ol style="width: 180mm; margin-left:-30px; list-style-type: lower-alpha; font-size: 9px;">
    <li style="padding-left: 5px; text-align:justify;"><strong>Precios si incluyen IGV</strong></li>
    <li style="padding-left: 5px; text-align:justify;">El precio total de esta propuesta ya está con descuento de paquete, por tanto este descuento de paquete no aplica para la venta de productos por separado. Los volúmenes y productos que forman parte de los paquetes aprobados por los clientes son considerados ventas finales. No son desglosables.</li>
    <li style="padding-left: 5px; text-align:justify;">El pedido es por el total de productos presupuestados, al que se le aplica el descuento dentro de la propuesta, cualquier cambio que se realice luego de aprobado el programa, si no se respetan el despacho programado, la empresa considerará los precios sin descuento.</li>        
    <li style="padding-left: 5px; text-align:justify;">El descuento de cada propuesta es independiente de otras propuestas, debido al volumen de compra (numero de Has, cantidad y litros de productos, etc.) El descuento aplica para el área presupuestada.</li>
    <li style="padding-left: 5px; text-align:justify;">Los precios pueden variar de una propuesta más reciente a otra anterior, debido al incremento de precios en los insumos.</li>
    <li style="padding-left: 5px; text-align:justify;">Forma de pago: A Tratar</li>
    <li style="padding-left: 5px; text-align:justify;">Validez de oferta 10 días</li>
    <li style="padding-left: 5px; text-align:justify;">Flete puesto en fundo: a tratar. Si la entrega se coordinara en fundo, la entrega de mercadería se hará en un solo envío, si el cliente deseara el envío fraccionado deberá adicionar un cargo mínimo de 120 nuevos soles o el equivalente al envío.</li>
    <li style="padding-left: 5px; text-align:justify;">La propuesta del presente programa está hecha en base a la fertilización convencional que es información proporcionada por el cliente, no por recomendación nuestra, pero si se le puede adicionar productos específicos para hacer mejoras en los cultivos. Por ello si hubiese algún cambio en la fertilización convencional del campo testigo, si hubiese testigo, favor de comunicárnoslo para realizar los cambios respectivos en los campos con Nutrición Micro Carbono HUMA GRO. Si observara alguna deficiencia en los campos con nuestros productos avísenos para hacer los reajustes necesarios.</li>
    <li style="padding-left: 5px; text-align:justify;">El presente programa puede incluir Nutrición Micro Carbono HUMA GRO foliar pero no las aplicaciones correspondientes al control de plagas y enfermedades (es un programa netamente nutricional).</li>
    <li style="padding-left: 5px; text-align:justify;">Las cantidades "TOTAL L/Lote" son las cantidades cotizadas por el área que figura en el cuadro anteriormente mencionado serán redondeadas a galoneras de 9.46 L si fuera necesario.</li>
    <li style="padding-left: 5px; text-align:justify;">Para la venta final se considerara la suma total del redondeo por despachar.</li>
    <li style="padding-left: 5px; text-align:justify;">Si tiene algún comentario no dude en comunicarse con nosotros al (01)368-3531, RPC 962383835, escríbenos a <a target="_top" href="mailto:acomercial@agromicrobiotech.com">acomercial@agromicrobiotech.com</a> o visite nuestra página web <a target="_top" href="http://nutricionmicrocarbono.com/">www.NutricionMicroCarbono.com</a></li>
</ol>